[tool.poetry]
name = "datalake-bundle"
version = "0.4.0b1"
description = "DataLake tables management bundle for the Bricksflow Framework"
readme = "README.md"
repository = "https://github.com/bricksflow/datalake-bundle"

license = "MIT"

authors = [
    "Jiri Koutny <jiri.koutny@datasentics.com>"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

include = ["*.yaml"]

packages = [
    { include = "datalakebundle", from = "src" },
]

[tool.poetry.dependencies]
python = "~3.7.3"
injecta = ">=0.7"
pyfony-bundles = "0.2.*"
console-bundle = "0.2.*"
databricks-bundle = "^0.2.4 || 0.3.* || 0.4.*"
simpleeval = "^0.9.10"

[tool.poetry.dev-dependencies]
pylint = "2.4.*"
pyfony = "^0.4.0"
pytest = "5.2.*"
databricks-connect = "^6.4.0"
py4j = "^0.10.9"

[app]
container-init = ["datalakebundle.containerInit", "initContainer"]
